# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/support/optimisation/DOpE.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Matrix_pb2 as Matrix__pb2
from message.support.optimisation import OptimiserTypes_pb2 as message_dot_support_dot_optimisation_dot_OptimiserTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/support/optimisation/DOpE.proto',
  package='protobuf.message.support.optimisation',
  syntax='proto3',
  serialized_pb=_b('\n\'message/support/optimisation/DOpE.proto\x12%protobuf.message.support.optimisation\x1a\x0cMatrix.proto\x1a\x31message/support/optimisation/OptimiserTypes.proto\"\x86\x01\n\x14RegisterOptimisation\x12\r\n\x05group\x18\x01 \x01(\t\x12\x0f\n\x07network\x18\x02 \x01(\x08\x12N\n\nparameters\x18\x03 \x01(\x0b\x32:.protobuf.message.support.optimisation.OptimiserParameters\"4\n\x11RequestParameters\x12\r\n\x05group\x18\x01 \x01(\t\x12\x10\n\x08nSamples\x18\x02 \x01(\r\"`\n\nParameters\x12\r\n\x05group\x18\x01 \x01(\t\x12\x12\n\ngeneration\x18\x02 \x01(\x05\x12\x15\n\x07samples\x18\x03 \x01(\x0b\x32\x04.mat\x12\x18\n\ncovariance\x18\x04 \x01(\x0b\x32\x04.matb\x06proto3')
  ,
  dependencies=[Matrix__pb2.DESCRIPTOR,message_dot_support_dot_optimisation_dot_OptimiserTypes__pb2.DESCRIPTOR,])




_REGISTEROPTIMISATION = _descriptor.Descriptor(
  name='RegisterOptimisation',
  full_name='protobuf.message.support.optimisation.RegisterOptimisation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='protobuf.message.support.optimisation.RegisterOptimisation.group', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='network', full_name='protobuf.message.support.optimisation.RegisterOptimisation.network', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='protobuf.message.support.optimisation.RegisterOptimisation.parameters', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=282,
)


_REQUESTPARAMETERS = _descriptor.Descriptor(
  name='RequestParameters',
  full_name='protobuf.message.support.optimisation.RequestParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='protobuf.message.support.optimisation.RequestParameters.group', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nSamples', full_name='protobuf.message.support.optimisation.RequestParameters.nSamples', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=336,
)


_PARAMETERS = _descriptor.Descriptor(
  name='Parameters',
  full_name='protobuf.message.support.optimisation.Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='protobuf.message.support.optimisation.Parameters.group', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generation', full_name='protobuf.message.support.optimisation.Parameters.generation', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='samples', full_name='protobuf.message.support.optimisation.Parameters.samples', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='protobuf.message.support.optimisation.Parameters.covariance', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=434,
)

_REGISTEROPTIMISATION.fields_by_name['parameters'].message_type = message_dot_support_dot_optimisation_dot_OptimiserTypes__pb2._OPTIMISERPARAMETERS
_PARAMETERS.fields_by_name['samples'].message_type = Matrix__pb2._MAT
_PARAMETERS.fields_by_name['covariance'].message_type = Matrix__pb2._MAT
DESCRIPTOR.message_types_by_name['RegisterOptimisation'] = _REGISTEROPTIMISATION
DESCRIPTOR.message_types_by_name['RequestParameters'] = _REQUESTPARAMETERS
DESCRIPTOR.message_types_by_name['Parameters'] = _PARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterOptimisation = _reflection.GeneratedProtocolMessageType('RegisterOptimisation', (_message.Message,), dict(
  DESCRIPTOR = _REGISTEROPTIMISATION,
  __module__ = 'message.support.optimisation.DOpE_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.support.optimisation.RegisterOptimisation)
  ))
_sym_db.RegisterMessage(RegisterOptimisation)

RequestParameters = _reflection.GeneratedProtocolMessageType('RequestParameters', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTPARAMETERS,
  __module__ = 'message.support.optimisation.DOpE_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.support.optimisation.RequestParameters)
  ))
_sym_db.RegisterMessage(RequestParameters)

Parameters = _reflection.GeneratedProtocolMessageType('Parameters', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERS,
  __module__ = 'message.support.optimisation.DOpE_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.support.optimisation.Parameters)
  ))
_sym_db.RegisterMessage(Parameters)


# @@protoc_insertion_point(module_scope)
