# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/support/optimisation/Episode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2
import Matrix_pb2 as Matrix__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/support/optimisation/Episode.proto',
  package='protobuf.message.support.optimisation',
  syntax='proto3',
  serialized_pb=_b('\n*message/support/optimisation/Episode.proto\x12%protobuf.message.support.optimisation\x1a\x0cVector.proto\x1a\x0cMatrix.proto\"\xd1\x01\n\x07\x45pisode\x12\r\n\x05group\x18\x01 \x01(\t\x12\x12\n\ngeneration\x18\x02 \x01(\x05\x12\x14\n\x06values\x18\x03 \x01(\x0b\x32\x04.vec\x12\x18\n\ncovariance\x18\x04 \x01(\x0b\x32\x04.mat\x12G\n\x07\x66itness\x18\x05 \x03(\x0b\x32\x36.protobuf.message.support.optimisation.Episode.Fitness\x1a*\n\x07\x46itness\x12\x0f\n\x07\x66itness\x18\x01 \x01(\x01\x12\x0e\n\x06weight\x18\x02 \x01(\x01\x62\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,Matrix__pb2.DESCRIPTOR,])




_EPISODE_FITNESS = _descriptor.Descriptor(
  name='Fitness',
  full_name='protobuf.message.support.optimisation.Episode.Fitness',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fitness', full_name='protobuf.message.support.optimisation.Episode.Fitness.fitness', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='protobuf.message.support.optimisation.Episode.Fitness.weight', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=323,
)

_EPISODE = _descriptor.Descriptor(
  name='Episode',
  full_name='protobuf.message.support.optimisation.Episode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='protobuf.message.support.optimisation.Episode.group', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generation', full_name='protobuf.message.support.optimisation.Episode.generation', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='protobuf.message.support.optimisation.Episode.values', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='protobuf.message.support.optimisation.Episode.covariance', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fitness', full_name='protobuf.message.support.optimisation.Episode.fitness', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EPISODE_FITNESS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=323,
)

_EPISODE_FITNESS.containing_type = _EPISODE
_EPISODE.fields_by_name['values'].message_type = Vector__pb2._VEC
_EPISODE.fields_by_name['covariance'].message_type = Matrix__pb2._MAT
_EPISODE.fields_by_name['fitness'].message_type = _EPISODE_FITNESS
DESCRIPTOR.message_types_by_name['Episode'] = _EPISODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Episode = _reflection.GeneratedProtocolMessageType('Episode', (_message.Message,), dict(

  Fitness = _reflection.GeneratedProtocolMessageType('Fitness', (_message.Message,), dict(
    DESCRIPTOR = _EPISODE_FITNESS,
    __module__ = 'message.support.optimisation.Episode_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.message.support.optimisation.Episode.Fitness)
    ))
  ,
  DESCRIPTOR = _EPISODE,
  __module__ = 'message.support.optimisation.Episode_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.support.optimisation.Episode)
  ))
_sym_db.RegisterMessage(Episode)
_sym_db.RegisterMessage(Episode.Fitness)


# @@protoc_insertion_point(module_scope)
