# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/support/optimisation/Estimate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2
import Matrix_pb2 as Matrix__pb2
from message.support.optimisation import Episode_pb2 as message_dot_support_dot_optimisation_dot_Episode__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/support/optimisation/Estimate.proto',
  package='protobuf.message.support.optimisation',
  syntax='proto3',
  serialized_pb=_b('\n+message/support/optimisation/Estimate.proto\x12%protobuf.message.support.optimisation\x1a\x0cVector.proto\x1a\x0cMatrix.proto\x1a*message/support/optimisation/Episode.proto\"\xe8\x01\n\x08\x45stimate\x12\r\n\x05group\x18\x01 \x01(\t\x12\x12\n\ngeneration\x18\x02 \x01(\x05\x12\x14\n\x06values\x18\x03 \x01(\x0b\x32\x04.vec\x12\x18\n\ncovariance\x18\x04 \x01(\x0b\x32\x04.mat\x12H\n\x10\x65stimate_episode\x18\x05 \x03(\x0b\x32..protobuf.message.support.optimisation.Episode\x12?\n\x07\x65pisode\x18\x06 \x03(\x0b\x32..protobuf.message.support.optimisation.Episodeb\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,Matrix__pb2.DESCRIPTOR,message_dot_support_dot_optimisation_dot_Episode__pb2.DESCRIPTOR,])




_ESTIMATE = _descriptor.Descriptor(
  name='Estimate',
  full_name='protobuf.message.support.optimisation.Estimate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='protobuf.message.support.optimisation.Estimate.group', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generation', full_name='protobuf.message.support.optimisation.Estimate.generation', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='protobuf.message.support.optimisation.Estimate.values', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='protobuf.message.support.optimisation.Estimate.covariance', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estimate_episode', full_name='protobuf.message.support.optimisation.Estimate.estimate_episode', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='episode', full_name='protobuf.message.support.optimisation.Estimate.episode', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=391,
)

_ESTIMATE.fields_by_name['values'].message_type = Vector__pb2._VEC
_ESTIMATE.fields_by_name['covariance'].message_type = Matrix__pb2._MAT
_ESTIMATE.fields_by_name['estimate_episode'].message_type = message_dot_support_dot_optimisation_dot_Episode__pb2._EPISODE
_ESTIMATE.fields_by_name['episode'].message_type = message_dot_support_dot_optimisation_dot_Episode__pb2._EPISODE
DESCRIPTOR.message_types_by_name['Estimate'] = _ESTIMATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Estimate = _reflection.GeneratedProtocolMessageType('Estimate', (_message.Message,), dict(
  DESCRIPTOR = _ESTIMATE,
  __module__ = 'message.support.optimisation.Estimate_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.support.optimisation.Estimate)
  ))
_sym_db.RegisterMessage(Estimate)


# @@protoc_insertion_point(module_scope)
