# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/support/optimisation/OptimiserTypes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Matrix_pb2 as Matrix__pb2
import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/support/optimisation/OptimiserTypes.proto',
  package='protobuf.message.support.optimisation',
  syntax='proto3',
  serialized_pb=_b('\n1message/support/optimisation/OptimiserTypes.proto\x12%protobuf.message.support.optimisation\x1a\x0cMatrix.proto\x1a\x0cVector.proto\"Y\n\x11OptimiserEstimate\x12\x12\n\ngeneration\x18\x01 \x01(\x05\x12\x16\n\x08\x65stimate\x18\x02 \x01(\x0b\x32\x04.vec\x12\x18\n\ncovariance\x18\x03 \x01(\x0b\x32\x04.mat\"\xa7\x01\n\x13OptimiserParameters\x12I\n\x07initial\x18\x01 \x01(\x0b\x32\x38.protobuf.message.support.optimisation.OptimiserEstimate\x12\x18\n\nupperBound\x18\x02 \x01(\x0b\x32\x04.vec\x12\x18\n\nlowerBound\x18\x03 \x01(\x0b\x32\x04.vec\x12\x11\n\tbatchSize\x18\x04 \x01(\rb\x06proto3')
  ,
  dependencies=[Matrix__pb2.DESCRIPTOR,Vector__pb2.DESCRIPTOR,])




_OPTIMISERESTIMATE = _descriptor.Descriptor(
  name='OptimiserEstimate',
  full_name='protobuf.message.support.optimisation.OptimiserEstimate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='generation', full_name='protobuf.message.support.optimisation.OptimiserEstimate.generation', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='estimate', full_name='protobuf.message.support.optimisation.OptimiserEstimate.estimate', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='protobuf.message.support.optimisation.OptimiserEstimate.covariance', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=209,
)


_OPTIMISERPARAMETERS = _descriptor.Descriptor(
  name='OptimiserParameters',
  full_name='protobuf.message.support.optimisation.OptimiserParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='initial', full_name='protobuf.message.support.optimisation.OptimiserParameters.initial', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upperBound', full_name='protobuf.message.support.optimisation.OptimiserParameters.upperBound', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lowerBound', full_name='protobuf.message.support.optimisation.OptimiserParameters.lowerBound', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batchSize', full_name='protobuf.message.support.optimisation.OptimiserParameters.batchSize', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=379,
)

_OPTIMISERESTIMATE.fields_by_name['estimate'].message_type = Vector__pb2._VEC
_OPTIMISERESTIMATE.fields_by_name['covariance'].message_type = Matrix__pb2._MAT
_OPTIMISERPARAMETERS.fields_by_name['initial'].message_type = _OPTIMISERESTIMATE
_OPTIMISERPARAMETERS.fields_by_name['upperBound'].message_type = Vector__pb2._VEC
_OPTIMISERPARAMETERS.fields_by_name['lowerBound'].message_type = Vector__pb2._VEC
DESCRIPTOR.message_types_by_name['OptimiserEstimate'] = _OPTIMISERESTIMATE
DESCRIPTOR.message_types_by_name['OptimiserParameters'] = _OPTIMISERPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OptimiserEstimate = _reflection.GeneratedProtocolMessageType('OptimiserEstimate', (_message.Message,), dict(
  DESCRIPTOR = _OPTIMISERESTIMATE,
  __module__ = 'message.support.optimisation.OptimiserTypes_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.support.optimisation.OptimiserEstimate)
  ))
_sym_db.RegisterMessage(OptimiserEstimate)

OptimiserParameters = _reflection.GeneratedProtocolMessageType('OptimiserParameters', (_message.Message,), dict(
  DESCRIPTOR = _OPTIMISERPARAMETERS,
  __module__ = 'message.support.optimisation.OptimiserTypes_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.support.optimisation.OptimiserParameters)
  ))
_sym_db.RegisterMessage(OptimiserParameters)


# @@protoc_insertion_point(module_scope)
