# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/input/CameraParameters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/input/CameraParameters.proto',
  package='protobuf.message.input',
  syntax='proto3',
  serialized_pb=_b('\n$message/input/CameraParameters.proto\x12\x16protobuf.message.input\x1a\x0cVector.proto\"\xd9\x03\n\x10\x43\x61meraParameters\x12\x1f\n\x0fimageSizePixels\x18\x01 \x01(\x0b\x32\x06.uvec2\x12\x12\n\x03\x46OV\x18\x02 \x01(\x0b\x32\x05.vec2\x12\x1c\n\x0c\x63\x65ntreOffset\x18\x03 \x01(\x0b\x32\x06.ivec2\x12\x41\n\x07pinhole\x18\x04 \x01(\x0b\x32\x30.protobuf.message.input.CameraParameters.Pinhole\x12?\n\x06radial\x18\x05 \x01(\x0b\x32/.protobuf.message.input.CameraParameters.Radial\x12?\n\x04lens\x18\x06 \x01(\x0e\x32\x31.protobuf.message.input.CameraParameters.LensType\x1a\x65\n\x07Pinhole\x12%\n\x16pixelsToTanThetaFactor\x18\x01 \x01(\x0b\x32\x05.vec2\x12\x19\n\x11\x66ocalLengthPixels\x18\x02 \x01(\x01\x12\x18\n\x10\x64istortionFactor\x18\x03 \x01(\x01\x1a!\n\x06Radial\x12\x17\n\x0fradiansPerPixel\x18\x01 \x01(\x01\"#\n\x08LensType\x12\x0b\n\x07PINHOLE\x10\x00\x12\n\n\x06RADIAL\x10\x01\x62\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,])



_CAMERAPARAMETERS_LENSTYPE = _descriptor.EnumDescriptor(
  name='LensType',
  full_name='protobuf.message.input.CameraParameters.LensType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PINHOLE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RADIAL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=517,
  serialized_end=552,
)
_sym_db.RegisterEnumDescriptor(_CAMERAPARAMETERS_LENSTYPE)


_CAMERAPARAMETERS_PINHOLE = _descriptor.Descriptor(
  name='Pinhole',
  full_name='protobuf.message.input.CameraParameters.Pinhole',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pixelsToTanThetaFactor', full_name='protobuf.message.input.CameraParameters.Pinhole.pixelsToTanThetaFactor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='focalLengthPixels', full_name='protobuf.message.input.CameraParameters.Pinhole.focalLengthPixels', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distortionFactor', full_name='protobuf.message.input.CameraParameters.Pinhole.distortionFactor', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=480,
)

_CAMERAPARAMETERS_RADIAL = _descriptor.Descriptor(
  name='Radial',
  full_name='protobuf.message.input.CameraParameters.Radial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='radiansPerPixel', full_name='protobuf.message.input.CameraParameters.Radial.radiansPerPixel', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=515,
)

_CAMERAPARAMETERS = _descriptor.Descriptor(
  name='CameraParameters',
  full_name='protobuf.message.input.CameraParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imageSizePixels', full_name='protobuf.message.input.CameraParameters.imageSizePixels', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FOV', full_name='protobuf.message.input.CameraParameters.FOV', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='centreOffset', full_name='protobuf.message.input.CameraParameters.centreOffset', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pinhole', full_name='protobuf.message.input.CameraParameters.pinhole', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radial', full_name='protobuf.message.input.CameraParameters.radial', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lens', full_name='protobuf.message.input.CameraParameters.lens', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CAMERAPARAMETERS_PINHOLE, _CAMERAPARAMETERS_RADIAL, ],
  enum_types=[
    _CAMERAPARAMETERS_LENSTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=552,
)

_CAMERAPARAMETERS_PINHOLE.fields_by_name['pixelsToTanThetaFactor'].message_type = Vector__pb2._VEC2
_CAMERAPARAMETERS_PINHOLE.containing_type = _CAMERAPARAMETERS
_CAMERAPARAMETERS_RADIAL.containing_type = _CAMERAPARAMETERS
_CAMERAPARAMETERS.fields_by_name['imageSizePixels'].message_type = Vector__pb2._UVEC2
_CAMERAPARAMETERS.fields_by_name['FOV'].message_type = Vector__pb2._VEC2
_CAMERAPARAMETERS.fields_by_name['centreOffset'].message_type = Vector__pb2._IVEC2
_CAMERAPARAMETERS.fields_by_name['pinhole'].message_type = _CAMERAPARAMETERS_PINHOLE
_CAMERAPARAMETERS.fields_by_name['radial'].message_type = _CAMERAPARAMETERS_RADIAL
_CAMERAPARAMETERS.fields_by_name['lens'].enum_type = _CAMERAPARAMETERS_LENSTYPE
_CAMERAPARAMETERS_LENSTYPE.containing_type = _CAMERAPARAMETERS
DESCRIPTOR.message_types_by_name['CameraParameters'] = _CAMERAPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraParameters = _reflection.GeneratedProtocolMessageType('CameraParameters', (_message.Message,), dict(

  Pinhole = _reflection.GeneratedProtocolMessageType('Pinhole', (_message.Message,), dict(
    DESCRIPTOR = _CAMERAPARAMETERS_PINHOLE,
    __module__ = 'message.input.CameraParameters_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.message.input.CameraParameters.Pinhole)
    ))
  ,

  Radial = _reflection.GeneratedProtocolMessageType('Radial', (_message.Message,), dict(
    DESCRIPTOR = _CAMERAPARAMETERS_RADIAL,
    __module__ = 'message.input.CameraParameters_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.message.input.CameraParameters.Radial)
    ))
  ,
  DESCRIPTOR = _CAMERAPARAMETERS,
  __module__ = 'message.input.CameraParameters_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.input.CameraParameters)
  ))
_sym_db.RegisterMessage(CameraParameters)
_sym_db.RegisterMessage(CameraParameters.Pinhole)
_sym_db.RegisterMessage(CameraParameters.Radial)


# @@protoc_insertion_point(module_scope)
