# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/input/ImageFragment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Matrix_pb2 as Matrix__pb2
from message.input import Image_pb2 as message_dot_input_dot_Image__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/input/ImageFragment.proto',
  package='protobuf.message.input',
  syntax='proto3',
  serialized_pb=_b('\n!message/input/ImageFragment.proto\x12\x16protobuf.message.input\x1a\x0cMatrix.proto\x1a\x19message/input/Image.proto\"v\n\rImageFragment\x12,\n\x05image\x18\x01 \x01(\x0b\x32\x1d.protobuf.message.input.Image\x12\r\n\x05start\x18\x05 \x01(\r\x12\x0b\n\x03\x65nd\x18\x06 \x01(\r\x12\x1b\n\x0b\x63\x61m_to_feet\x18\x07 \x01(\x0b\x32\x06.fmat4b\x06proto3')
  ,
  dependencies=[Matrix__pb2.DESCRIPTOR,message_dot_input_dot_Image__pb2.DESCRIPTOR,])




_IMAGEFRAGMENT = _descriptor.Descriptor(
  name='ImageFragment',
  full_name='protobuf.message.input.ImageFragment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='protobuf.message.input.ImageFragment.image', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='protobuf.message.input.ImageFragment.start', index=1,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='protobuf.message.input.ImageFragment.end', index=2,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cam_to_feet', full_name='protobuf.message.input.ImageFragment.cam_to_feet', index=3,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=220,
)

_IMAGEFRAGMENT.fields_by_name['image'].message_type = message_dot_input_dot_Image__pb2._IMAGE
_IMAGEFRAGMENT.fields_by_name['cam_to_feet'].message_type = Matrix__pb2._FMAT4
DESCRIPTOR.message_types_by_name['ImageFragment'] = _IMAGEFRAGMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageFragment = _reflection.GeneratedProtocolMessageType('ImageFragment', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEFRAGMENT,
  __module__ = 'message.input.ImageFragment_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.input.ImageFragment)
  ))
_sym_db.RegisterMessage(ImageFragment)


# @@protoc_insertion_point(module_scope)
