# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/input/JoystickEvent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/input/JoystickEvent.proto',
  package='protobuf.message.input',
  syntax='proto3',
  serialized_pb=_b('\n!message/input/JoystickEvent.proto\x12\x16protobuf.message.input\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x05\n\rJoystickEvent\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05value\x18\x02 \x01(\x05\x12=\n\x04type\x18\x03 \x01(\x0e\x32/.protobuf.message.input.JoystickEvent.EventType\x12\x38\n\x04\x61xis\x18\x04 \x01(\x0e\x32*.protobuf.message.input.JoystickEvent.Axis\x12<\n\x06\x62utton\x18\x05 \x01(\x0e\x32,.protobuf.message.input.JoystickEvent.Button\"9\n\tEventType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x42UTTON\x10\x01\x12\x08\n\x04\x41XIS\x10\x02\x12\t\n\x04INIT\x10\x80\x01\"\x8c\x01\n\x04\x41xis\x12\x1c\n\x18LEFT_JOYSTICK_HORIZONTAL\x10\x00\x12\x1a\n\x16LEFT_JOYSTICK_VERTICAL\x10\x01\x12\x06\n\x02L2\x10\x02\x12\x1d\n\x19RIGHT_JOYSTICK_HORIZONTAL\x10\x03\x12\x1b\n\x17RIGHT_JOYSTICK_VERTICAL\x10\x04\x12\x06\n\x02R2\x10\x05\"\xca\x01\n\x06\x42utton\x12\t\n\x05\x43ROSS\x10\x00\x12\n\n\x06\x43IRCLE\x10\x01\x12\x0c\n\x08TRIANGLE\x10\x02\x12\n\n\x06SQUARE\x10\x03\x12\x06\n\x02L1\x10\x04\x12\x06\n\x02R1\x10\x05\x12\n\n\x06SELECT\x10\x08\x12\t\n\x05START\x10\t\x12\x06\n\x02PS\x10\n\x12\x11\n\rLEFT_JOYSTICK\x10\x0b\x12\x12\n\x0eRIGHT_JOYSTICK\x10\x0c\x12\x0b\n\x07\x44PAD_UP\x10\r\x12\r\n\tDPAD_DOWN\x10\x0e\x12\r\n\tDPAD_LEFT\x10\x0f\x12\x0e\n\nDPAD_RIGHT\x10\x10\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_JOYSTICKEVENT_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='protobuf.message.input.JoystickEvent.EventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUTTON', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AXIS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INIT', index=3, number=128,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=357,
  serialized_end=414,
)
_sym_db.RegisterEnumDescriptor(_JOYSTICKEVENT_EVENTTYPE)

_JOYSTICKEVENT_AXIS = _descriptor.EnumDescriptor(
  name='Axis',
  full_name='protobuf.message.input.JoystickEvent.Axis',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEFT_JOYSTICK_HORIZONTAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_JOYSTICK_VERTICAL', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='L2', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_JOYSTICK_HORIZONTAL', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_JOYSTICK_VERTICAL', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='R2', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=417,
  serialized_end=557,
)
_sym_db.RegisterEnumDescriptor(_JOYSTICKEVENT_AXIS)

_JOYSTICKEVENT_BUTTON = _descriptor.EnumDescriptor(
  name='Button',
  full_name='protobuf.message.input.JoystickEvent.Button',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CROSS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CIRCLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIANGLE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SQUARE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='L1', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='R1', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SELECT', index=6, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START', index=7, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PS', index=8, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_JOYSTICK', index=9, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_JOYSTICK', index=10, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DPAD_UP', index=11, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DPAD_DOWN', index=12, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DPAD_LEFT', index=13, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DPAD_RIGHT', index=14, number=16,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=560,
  serialized_end=762,
)
_sym_db.RegisterEnumDescriptor(_JOYSTICKEVENT_BUTTON)


_JOYSTICKEVENT = _descriptor.Descriptor(
  name='JoystickEvent',
  full_name='protobuf.message.input.JoystickEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='protobuf.message.input.JoystickEvent.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='protobuf.message.input.JoystickEvent.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='protobuf.message.input.JoystickEvent.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='axis', full_name='protobuf.message.input.JoystickEvent.axis', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='button', full_name='protobuf.message.input.JoystickEvent.button', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _JOYSTICKEVENT_EVENTTYPE,
    _JOYSTICKEVENT_AXIS,
    _JOYSTICKEVENT_BUTTON,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=762,
)

_JOYSTICKEVENT.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_JOYSTICKEVENT.fields_by_name['type'].enum_type = _JOYSTICKEVENT_EVENTTYPE
_JOYSTICKEVENT.fields_by_name['axis'].enum_type = _JOYSTICKEVENT_AXIS
_JOYSTICKEVENT.fields_by_name['button'].enum_type = _JOYSTICKEVENT_BUTTON
_JOYSTICKEVENT_EVENTTYPE.containing_type = _JOYSTICKEVENT
_JOYSTICKEVENT_AXIS.containing_type = _JOYSTICKEVENT
_JOYSTICKEVENT_BUTTON.containing_type = _JOYSTICKEVENT
DESCRIPTOR.message_types_by_name['JoystickEvent'] = _JOYSTICKEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JoystickEvent = _reflection.GeneratedProtocolMessageType('JoystickEvent', (_message.Message,), dict(
  DESCRIPTOR = _JOYSTICKEVENT,
  __module__ = 'message.input.JoystickEvent_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.input.JoystickEvent)
  ))
_sym_db.RegisterMessage(JoystickEvent)


# @@protoc_insertion_point(module_scope)
