# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/input/PostureRecognition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/input/PostureRecognition.proto',
  package='protobuf.message.input',
  syntax='proto3',
  serialized_pb=_b('\n&message/input/PostureRecognition.proto\x12\x16protobuf.message.input\"\x11\n\x0fWalkingDetected\"\x11\n\x0f\x42\x65ndingDetected\"\x11\n\x0fKickingDetected\"\x11\n\x0fSittingDetected\"\x12\n\x10StandingDetected\"2\n\x0f\x46\x61llingDetected\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x62\x06proto3')
)




_WALKINGDETECTED = _descriptor.Descriptor(
  name='WalkingDetected',
  full_name='protobuf.message.input.WalkingDetected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=83,
)


_BENDINGDETECTED = _descriptor.Descriptor(
  name='BendingDetected',
  full_name='protobuf.message.input.BendingDetected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=102,
)


_KICKINGDETECTED = _descriptor.Descriptor(
  name='KickingDetected',
  full_name='protobuf.message.input.KickingDetected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=121,
)


_SITTINGDETECTED = _descriptor.Descriptor(
  name='SittingDetected',
  full_name='protobuf.message.input.SittingDetected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=140,
)


_STANDINGDETECTED = _descriptor.Descriptor(
  name='StandingDetected',
  full_name='protobuf.message.input.StandingDetected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=160,
)


_FALLINGDETECTED = _descriptor.Descriptor(
  name='FallingDetected',
  full_name='protobuf.message.input.FallingDetected',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='protobuf.message.input.FallingDetected.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='protobuf.message.input.FallingDetected.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='protobuf.message.input.FallingDetected.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=212,
)

DESCRIPTOR.message_types_by_name['WalkingDetected'] = _WALKINGDETECTED
DESCRIPTOR.message_types_by_name['BendingDetected'] = _BENDINGDETECTED
DESCRIPTOR.message_types_by_name['KickingDetected'] = _KICKINGDETECTED
DESCRIPTOR.message_types_by_name['SittingDetected'] = _SITTINGDETECTED
DESCRIPTOR.message_types_by_name['StandingDetected'] = _STANDINGDETECTED
DESCRIPTOR.message_types_by_name['FallingDetected'] = _FALLINGDETECTED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WalkingDetected = _reflection.GeneratedProtocolMessageType('WalkingDetected', (_message.Message,), dict(
  DESCRIPTOR = _WALKINGDETECTED,
  __module__ = 'message.input.PostureRecognition_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.input.WalkingDetected)
  ))
_sym_db.RegisterMessage(WalkingDetected)

BendingDetected = _reflection.GeneratedProtocolMessageType('BendingDetected', (_message.Message,), dict(
  DESCRIPTOR = _BENDINGDETECTED,
  __module__ = 'message.input.PostureRecognition_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.input.BendingDetected)
  ))
_sym_db.RegisterMessage(BendingDetected)

KickingDetected = _reflection.GeneratedProtocolMessageType('KickingDetected', (_message.Message,), dict(
  DESCRIPTOR = _KICKINGDETECTED,
  __module__ = 'message.input.PostureRecognition_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.input.KickingDetected)
  ))
_sym_db.RegisterMessage(KickingDetected)

SittingDetected = _reflection.GeneratedProtocolMessageType('SittingDetected', (_message.Message,), dict(
  DESCRIPTOR = _SITTINGDETECTED,
  __module__ = 'message.input.PostureRecognition_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.input.SittingDetected)
  ))
_sym_db.RegisterMessage(SittingDetected)

StandingDetected = _reflection.GeneratedProtocolMessageType('StandingDetected', (_message.Message,), dict(
  DESCRIPTOR = _STANDINGDETECTED,
  __module__ = 'message.input.PostureRecognition_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.input.StandingDetected)
  ))
_sym_db.RegisterMessage(StandingDetected)

FallingDetected = _reflection.GeneratedProtocolMessageType('FallingDetected', (_message.Message,), dict(
  DESCRIPTOR = _FALLINGDETECTED,
  __module__ = 'message.input.PostureRecognition_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.input.FallingDetected)
  ))
_sym_db.RegisterMessage(FallingDetected)


# @@protoc_insertion_point(module_scope)
