# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/input/PresenceUserState.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Matrix_pb2 as Matrix__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/input/PresenceUserState.proto',
  package='protobuf.message.input',
  syntax='proto3',
  serialized_pb=_b('\n%message/input/PresenceUserState.proto\x12\x16protobuf.message.input\x1a\x0cMatrix.proto\".\n\x11PresenceUserState\x12\x19\n\thead_pose\x18\x01 \x01(\x0b\x32\x06.fmat4b\x06proto3')
  ,
  dependencies=[Matrix__pb2.DESCRIPTOR,])




_PRESENCEUSERSTATE = _descriptor.Descriptor(
  name='PresenceUserState',
  full_name='protobuf.message.input.PresenceUserState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='head_pose', full_name='protobuf.message.input.PresenceUserState.head_pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=125,
)

_PRESENCEUSERSTATE.fields_by_name['head_pose'].message_type = Matrix__pb2._FMAT4
DESCRIPTOR.message_types_by_name['PresenceUserState'] = _PRESENCEUSERSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PresenceUserState = _reflection.GeneratedProtocolMessageType('PresenceUserState', (_message.Message,), dict(
  DESCRIPTOR = _PRESENCEUSERSTATE,
  __module__ = 'message.input.PresenceUserState_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.input.PresenceUserState)
  ))
_sym_db.RegisterMessage(PresenceUserState)


# @@protoc_insertion_point(module_scope)
