# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/support/ServoHealthTestData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from message.platform.darwin import DarwinSensors_pb2 as message_dot_platform_dot_darwin_dot_DarwinSensors__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/support/ServoHealthTestData.proto',
  package='protobuf.message.support',
  syntax='proto3',
  serialized_pb=_b('\n)message/support/ServoHealthTestData.proto\x12\x18protobuf.message.support\x1a+message/platform/darwin/DarwinSensors.proto\"\x99\x04\n\x13ServoHealthTestData\x12\x42\n\x05state\x18\x01 \x01(\x0e\x32\x33.protobuf.message.support.ServoHealthTestData.State\x12@\n\x07sensors\x18\x02 \x01(\x0b\x32/.protobuf.message.platform.darwin.DarwinSensors\"\xfb\x02\n\x05State\x12\x0e\n\nINITIALISE\x10\x00\x12\n\n\x06MOVE_1\x10\x01\x12\t\n\x05\x45LBOW\x10\x02\x12\n\n\x06MOVE_2\x10\x03\x12\x12\n\x0eSHOULDER_PITCH\x10\x04\x12\x13\n\x0fSHOULDER_MOVE_1\x10\x05\x12\x11\n\rSHOULDER_ROLL\x10\x06\x12\n\n\x06MOVE_3\x10\x07\x12\x0e\n\nHEAD_PITCH\x10\x08\x12\n\n\x06MOVE_4\x10\t\x12\x0c\n\x08HEAD_YAW\x10\n\x12\x0b\n\x07LAYDOWN\x10\x0b\x12\x0c\n\x08HIP_ROLL\x10\x0c\x12\x0e\n\nHIP_MOVE_1\x10\r\x12\x0b\n\x07HIP_YAW\x10\x0e\x12\x0e\n\nHIP_MOVE_2\x10\x0f\x12\x0f\n\x0b\x41NKLE_PITCH\x10\x10\x12\x0e\n\nANKLE_MOVE\x10\x11\x12\x0e\n\nANKLE_ROLL\x10\x12\x12\r\n\tKNEE_MOVE\x10\x13\x12\x08\n\x04KNEE\x10\x14\x12\x0f\n\x0bKNEE_MOVE_2\x10\x15\x12\r\n\tHIP_PITCH\x10\x16\x12\r\n\tLAYDOWN_2\x10\x17\x12\x0c\n\x08\x46INISHED\x10\x18\x62\x06proto3')
  ,
  dependencies=[message_dot_platform_dot_darwin_dot_DarwinSensors__pb2.DESCRIPTOR,])



_SERVOHEALTHTESTDATA_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='protobuf.message.support.ServoHealthTestData.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INITIALISE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOVE_1', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ELBOW', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOVE_2', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHOULDER_PITCH', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHOULDER_MOVE_1', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHOULDER_ROLL', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOVE_3', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEAD_PITCH', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MOVE_4', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEAD_YAW', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAYDOWN', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIP_ROLL', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIP_MOVE_1', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIP_YAW', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIP_MOVE_2', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANKLE_PITCH', index=16, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANKLE_MOVE', index=17, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANKLE_ROLL', index=18, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KNEE_MOVE', index=19, number=19,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KNEE', index=20, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KNEE_MOVE_2', index=21, number=21,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HIP_PITCH', index=22, number=22,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAYDOWN_2', index=23, number=23,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISHED', index=24, number=24,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=275,
  serialized_end=654,
)
_sym_db.RegisterEnumDescriptor(_SERVOHEALTHTESTDATA_STATE)


_SERVOHEALTHTESTDATA = _descriptor.Descriptor(
  name='ServoHealthTestData',
  full_name='protobuf.message.support.ServoHealthTestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='protobuf.message.support.ServoHealthTestData.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensors', full_name='protobuf.message.support.ServoHealthTestData.sensors', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVOHEALTHTESTDATA_STATE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=654,
)

_SERVOHEALTHTESTDATA.fields_by_name['state'].enum_type = _SERVOHEALTHTESTDATA_STATE
_SERVOHEALTHTESTDATA.fields_by_name['sensors'].message_type = message_dot_platform_dot_darwin_dot_DarwinSensors__pb2._DARWINSENSORS
_SERVOHEALTHTESTDATA_STATE.containing_type = _SERVOHEALTHTESTDATA
DESCRIPTOR.message_types_by_name['ServoHealthTestData'] = _SERVOHEALTHTESTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServoHealthTestData = _reflection.GeneratedProtocolMessageType('ServoHealthTestData', (_message.Message,), dict(
  DESCRIPTOR = _SERVOHEALTHTESTDATA,
  __module__ = 'message.support.ServoHealthTestData_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.support.ServoHealthTestData)
  ))
_sym_db.RegisterMessage(ServoHealthTestData)


# @@protoc_insertion_point(module_scope)
