# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/research/AutoClassifierPixels.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/research/AutoClassifierPixels.proto',
  package='protobuf.message.research',
  syntax='proto3',
  serialized_pb=_b('\n+message/research/AutoClassifierPixels.proto\x12\x19protobuf.message.research\">\n\x14\x41utoClassifierPixels\x12\x0e\n\x06pixels\x18\x01 \x03(\r\x12\x16\n\x0e\x63lassification\x18\x02 \x01(\rb\x06proto3')
)




_AUTOCLASSIFIERPIXELS = _descriptor.Descriptor(
  name='AutoClassifierPixels',
  full_name='protobuf.message.research.AutoClassifierPixels',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pixels', full_name='protobuf.message.research.AutoClassifierPixels.pixels', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classification', full_name='protobuf.message.research.AutoClassifierPixels.classification', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['AutoClassifierPixels'] = _AUTOCLASSIFIERPIXELS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AutoClassifierPixels = _reflection.GeneratedProtocolMessageType('AutoClassifierPixels', (_message.Message,), dict(
  DESCRIPTOR = _AUTOCLASSIFIERPIXELS,
  __module__ = 'message.research.AutoClassifierPixels_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.research.AutoClassifierPixels)
  ))
_sym_db.RegisterMessage(AutoClassifierPixels)


# @@protoc_insertion_point(module_scope)
