# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/vision/LookUpTable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/vision/LookUpTable.proto',
  package='protobuf.message.vision',
  syntax='proto3',
  serialized_pb=_b('\n message/vision/LookUpTable.proto\x12\x17protobuf.message.vision\"N\n\x0bLookUpTable\x12\r\n\x05table\x18\x01 \x01(\x0c\x12\x0e\n\x06\x62its_y\x18\x02 \x01(\r\x12\x0f\n\x07\x62its_cb\x18\x03 \x01(\r\x12\x0f\n\x07\x62its_cr\x18\x04 \x01(\r\"\x11\n\x0fSaveLookUpTableb\x06proto3')
)




_LOOKUPTABLE = _descriptor.Descriptor(
  name='LookUpTable',
  full_name='protobuf.message.vision.LookUpTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='protobuf.message.vision.LookUpTable.table', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bits_y', full_name='protobuf.message.vision.LookUpTable.bits_y', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bits_cb', full_name='protobuf.message.vision.LookUpTable.bits_cb', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bits_cr', full_name='protobuf.message.vision.LookUpTable.bits_cr', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=139,
)


_SAVELOOKUPTABLE = _descriptor.Descriptor(
  name='SaveLookUpTable',
  full_name='protobuf.message.vision.SaveLookUpTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=158,
)

DESCRIPTOR.message_types_by_name['LookUpTable'] = _LOOKUPTABLE
DESCRIPTOR.message_types_by_name['SaveLookUpTable'] = _SAVELOOKUPTABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LookUpTable = _reflection.GeneratedProtocolMessageType('LookUpTable', (_message.Message,), dict(
  DESCRIPTOR = _LOOKUPTABLE,
  __module__ = 'message.vision.LookUpTable_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.vision.LookUpTable)
  ))
_sym_db.RegisterMessage(LookUpTable)

SaveLookUpTable = _reflection.GeneratedProtocolMessageType('SaveLookUpTable', (_message.Message,), dict(
  DESCRIPTOR = _SAVELOOKUPTABLE,
  __module__ = 'message.vision.LookUpTable_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.vision.SaveLookUpTable)
  ))
_sym_db.RegisterMessage(SaveLookUpTable)


# @@protoc_insertion_point(module_scope)
