# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/vision/VisualMesh.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/vision/VisualMesh.proto',
  package='protobuf.message.vision',
  syntax='proto3',
  serialized_pb=_b('\n\x1fmessage/vision/VisualMesh.proto\x12\x17protobuf.message.vision\x1a\x0cVector.proto\"\xcc\x02\n\nVisualMesh\x12\x11\n\tcamera_id\x18\x01 \x01(\r\x12\x35\n\x04mesh\x18\x02 \x03(\x0b\x32\'.protobuf.message.vision.VisualMesh.Row\x12\x0f\n\x07indices\x18\x03 \x03(\x05\x12\x1d\n\rneighbourhood\x18\x04 \x03(\x0b\x32\x06.ivec6\x12\x1b\n\x0b\x63oordinates\x18\x05 \x03(\x0b\x32\x06.ivec2\x12K\n\x0f\x63lassifications\x18\x06 \x03(\x0b\x32\x32.protobuf.message.vision.VisualMesh.Classification\x1a$\n\x03Row\x12\x0b\n\x03phi\x18\x01 \x01(\x02\x12\x10\n\x08segments\x18\x02 \x01(\x05\x1a\x34\n\x0e\x43lassification\x12\x12\n\ndimensions\x18\x01 \x01(\x05\x12\x0e\n\x06values\x18\x02 \x03(\x02\x62\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,])




_VISUALMESH_ROW = _descriptor.Descriptor(
  name='Row',
  full_name='protobuf.message.vision.VisualMesh.Row',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phi', full_name='protobuf.message.vision.VisualMesh.Row.phi', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='segments', full_name='protobuf.message.vision.VisualMesh.Row.segments', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=353,
)

_VISUALMESH_CLASSIFICATION = _descriptor.Descriptor(
  name='Classification',
  full_name='protobuf.message.vision.VisualMesh.Classification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimensions', full_name='protobuf.message.vision.VisualMesh.Classification.dimensions', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='protobuf.message.vision.VisualMesh.Classification.values', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=407,
)

_VISUALMESH = _descriptor.Descriptor(
  name='VisualMesh',
  full_name='protobuf.message.vision.VisualMesh',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_id', full_name='protobuf.message.vision.VisualMesh.camera_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mesh', full_name='protobuf.message.vision.VisualMesh.mesh', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='indices', full_name='protobuf.message.vision.VisualMesh.indices', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neighbourhood', full_name='protobuf.message.vision.VisualMesh.neighbourhood', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coordinates', full_name='protobuf.message.vision.VisualMesh.coordinates', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classifications', full_name='protobuf.message.vision.VisualMesh.classifications', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VISUALMESH_ROW, _VISUALMESH_CLASSIFICATION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=407,
)

_VISUALMESH_ROW.containing_type = _VISUALMESH
_VISUALMESH_CLASSIFICATION.containing_type = _VISUALMESH
_VISUALMESH.fields_by_name['mesh'].message_type = _VISUALMESH_ROW
_VISUALMESH.fields_by_name['neighbourhood'].message_type = Vector__pb2._IVEC6
_VISUALMESH.fields_by_name['coordinates'].message_type = Vector__pb2._IVEC2
_VISUALMESH.fields_by_name['classifications'].message_type = _VISUALMESH_CLASSIFICATION
DESCRIPTOR.message_types_by_name['VisualMesh'] = _VISUALMESH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VisualMesh = _reflection.GeneratedProtocolMessageType('VisualMesh', (_message.Message,), dict(

  Row = _reflection.GeneratedProtocolMessageType('Row', (_message.Message,), dict(
    DESCRIPTOR = _VISUALMESH_ROW,
    __module__ = 'message.vision.VisualMesh_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.message.vision.VisualMesh.Row)
    ))
  ,

  Classification = _reflection.GeneratedProtocolMessageType('Classification', (_message.Message,), dict(
    DESCRIPTOR = _VISUALMESH_CLASSIFICATION,
    __module__ = 'message.vision.VisualMesh_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.message.vision.VisualMesh.Classification)
    ))
  ,
  DESCRIPTOR = _VISUALMESH,
  __module__ = 'message.vision.VisualMesh_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.vision.VisualMesh)
  ))
_sym_db.RegisterMessage(VisualMesh)
_sym_db.RegisterMessage(VisualMesh.Row)
_sym_db.RegisterMessage(VisualMesh.Classification)


# @@protoc_insertion_point(module_scope)
