# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/research/scriptoptimizer/OptimizeScript.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/research/scriptoptimizer/OptimizeScript.proto',
  package='protobuf.message.research.scriptoptimizer',
  syntax='proto3',
  serialized_pb=_b('\n5message/research/scriptoptimizer/OptimizeScript.proto\x12)protobuf.message.research.scriptoptimizer\"\xba\x02\n\x0eOptimizeScript\x12\x0e\n\x06target\x18\x01 \x01(\t\x12\x11\n\titeration\x18\x02 \x01(\r\x12\x10\n\x08metadata\x18\x03 \x01(\t\x12O\n\x06\x66rames\x18\x04 \x03(\x0b\x32?.protobuf.message.research.scriptoptimizer.OptimizeScript.Frame\x1a\x34\n\x06Target\x12\n\n\x02id\x18\x01 \x01(\r\x12\x10\n\x08position\x18\x02 \x01(\x02\x12\x0c\n\x04gain\x18\x03 \x01(\x02\x1al\n\x05\x46rame\x12\x10\n\x08\x64uration\x18\x01 \x01(\r\x12Q\n\x07targets\x18\x02 \x03(\x0b\x32@.protobuf.message.research.scriptoptimizer.OptimizeScript.Targetb\x06proto3')
)




_OPTIMIZESCRIPT_TARGET = _descriptor.Descriptor(
  name='Target',
  full_name='protobuf.message.research.scriptoptimizer.OptimizeScript.Target',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf.message.research.scriptoptimizer.OptimizeScript.Target.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='protobuf.message.research.scriptoptimizer.OptimizeScript.Target.position', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gain', full_name='protobuf.message.research.scriptoptimizer.OptimizeScript.Target.gain', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=305,
)

_OPTIMIZESCRIPT_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='protobuf.message.research.scriptoptimizer.OptimizeScript.Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='protobuf.message.research.scriptoptimizer.OptimizeScript.Frame.duration', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='targets', full_name='protobuf.message.research.scriptoptimizer.OptimizeScript.Frame.targets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=415,
)

_OPTIMIZESCRIPT = _descriptor.Descriptor(
  name='OptimizeScript',
  full_name='protobuf.message.research.scriptoptimizer.OptimizeScript',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='protobuf.message.research.scriptoptimizer.OptimizeScript.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iteration', full_name='protobuf.message.research.scriptoptimizer.OptimizeScript.iteration', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='protobuf.message.research.scriptoptimizer.OptimizeScript.metadata', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frames', full_name='protobuf.message.research.scriptoptimizer.OptimizeScript.frames', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_OPTIMIZESCRIPT_TARGET, _OPTIMIZESCRIPT_FRAME, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=415,
)

_OPTIMIZESCRIPT_TARGET.containing_type = _OPTIMIZESCRIPT
_OPTIMIZESCRIPT_FRAME.fields_by_name['targets'].message_type = _OPTIMIZESCRIPT_TARGET
_OPTIMIZESCRIPT_FRAME.containing_type = _OPTIMIZESCRIPT
_OPTIMIZESCRIPT.fields_by_name['frames'].message_type = _OPTIMIZESCRIPT_FRAME
DESCRIPTOR.message_types_by_name['OptimizeScript'] = _OPTIMIZESCRIPT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OptimizeScript = _reflection.GeneratedProtocolMessageType('OptimizeScript', (_message.Message,), dict(

  Target = _reflection.GeneratedProtocolMessageType('Target', (_message.Message,), dict(
    DESCRIPTOR = _OPTIMIZESCRIPT_TARGET,
    __module__ = 'message.research.scriptoptimizer.OptimizeScript_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.message.research.scriptoptimizer.OptimizeScript.Target)
    ))
  ,

  Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), dict(
    DESCRIPTOR = _OPTIMIZESCRIPT_FRAME,
    __module__ = 'message.research.scriptoptimizer.OptimizeScript_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.message.research.scriptoptimizer.OptimizeScript.Frame)
    ))
  ,
  DESCRIPTOR = _OPTIMIZESCRIPT,
  __module__ = 'message.research.scriptoptimizer.OptimizeScript_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.research.scriptoptimizer.OptimizeScript)
  ))
_sym_db.RegisterMessage(OptimizeScript)
_sym_db.RegisterMessage(OptimizeScript.Target)
_sym_db.RegisterMessage(OptimizeScript.Frame)


# @@protoc_insertion_point(module_scope)
