# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/research/scriptoptimizer/OptimizeScriptResult.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from message.input import Sensors_pb2 as message_dot_input_dot_Sensors__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/research/scriptoptimizer/OptimizeScriptResult.proto',
  package='protobuf.message.research.scriptoptimizer',
  syntax='proto3',
  serialized_pb=_b('\n;message/research/scriptoptimizer/OptimizeScriptResult.proto\x12)protobuf.message.research.scriptoptimizer\x1a\x1bmessage/input/Sensors.proto\"m\n\x14OptimizeScriptResult\x12\x11\n\titeration\x18\x01 \x01(\r\x12\x10\n\x08metadata\x18\x02 \x01(\t\x12\x30\n\x07sensors\x18\x03 \x03(\x0b\x32\x1f.protobuf.message.input.Sensorsb\x06proto3')
  ,
  dependencies=[message_dot_input_dot_Sensors__pb2.DESCRIPTOR,])




_OPTIMIZESCRIPTRESULT = _descriptor.Descriptor(
  name='OptimizeScriptResult',
  full_name='protobuf.message.research.scriptoptimizer.OptimizeScriptResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iteration', full_name='protobuf.message.research.scriptoptimizer.OptimizeScriptResult.iteration', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='protobuf.message.research.scriptoptimizer.OptimizeScriptResult.metadata', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensors', full_name='protobuf.message.research.scriptoptimizer.OptimizeScriptResult.sensors', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=244,
)

_OPTIMIZESCRIPTRESULT.fields_by_name['sensors'].message_type = message_dot_input_dot_Sensors__pb2._SENSORS
DESCRIPTOR.message_types_by_name['OptimizeScriptResult'] = _OPTIMIZESCRIPTRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OptimizeScriptResult = _reflection.GeneratedProtocolMessageType('OptimizeScriptResult', (_message.Message,), dict(
  DESCRIPTOR = _OPTIMIZESCRIPTRESULT,
  __module__ = 'message.research.scriptoptimizer.OptimizeScriptResult_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.research.scriptoptimizer.OptimizeScriptResult)
  ))
_sym_db.RegisterMessage(OptimizeScriptResult)


# @@protoc_insertion_point(module_scope)
