# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/behaviour/KickPlan.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/behaviour/KickPlan.proto',
  package='protobuf.message.behaviour',
  syntax='proto3',
  serialized_pb=_b('\n message/behaviour/KickPlan.proto\x12\x1aprotobuf.message.behaviour\x1a\x0cVector.proto\"\x89\x01\n\x08KickPlan\x12\x15\n\x06target\x18\x01 \x01(\x0b\x32\x05.vec2\x12?\n\x08kickType\x18\x02 \x01(\x0e\x32-.protobuf.message.behaviour.KickPlan.KickType\"%\n\x08KickType\x12\x0c\n\x08SCRIPTED\x10\x00\x12\x0b\n\x07IK_KICK\x10\x01\"\x1b\n\x0bWantsToKick\x12\x0c\n\x04kick\x18\x01 \x01(\x08\x62\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,])



_KICKPLAN_KICKTYPE = _descriptor.EnumDescriptor(
  name='KickType',
  full_name='protobuf.message.behaviour.KickPlan.KickType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SCRIPTED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IK_KICK', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=179,
  serialized_end=216,
)
_sym_db.RegisterEnumDescriptor(_KICKPLAN_KICKTYPE)


_KICKPLAN = _descriptor.Descriptor(
  name='KickPlan',
  full_name='protobuf.message.behaviour.KickPlan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='protobuf.message.behaviour.KickPlan.target', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kickType', full_name='protobuf.message.behaviour.KickPlan.kickType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _KICKPLAN_KICKTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=216,
)


_WANTSTOKICK = _descriptor.Descriptor(
  name='WantsToKick',
  full_name='protobuf.message.behaviour.WantsToKick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kick', full_name='protobuf.message.behaviour.WantsToKick.kick', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=245,
)

_KICKPLAN.fields_by_name['target'].message_type = Vector__pb2._VEC2
_KICKPLAN.fields_by_name['kickType'].enum_type = _KICKPLAN_KICKTYPE
_KICKPLAN_KICKTYPE.containing_type = _KICKPLAN
DESCRIPTOR.message_types_by_name['KickPlan'] = _KICKPLAN
DESCRIPTOR.message_types_by_name['WantsToKick'] = _WANTSTOKICK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KickPlan = _reflection.GeneratedProtocolMessageType('KickPlan', (_message.Message,), dict(
  DESCRIPTOR = _KICKPLAN,
  __module__ = 'message.behaviour.KickPlan_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.behaviour.KickPlan)
  ))
_sym_db.RegisterMessage(KickPlan)

WantsToKick = _reflection.GeneratedProtocolMessageType('WantsToKick', (_message.Message,), dict(
  DESCRIPTOR = _WANTSTOKICK,
  __module__ = 'message.behaviour.KickPlan_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.behaviour.WantsToKick)
  ))
_sym_db.RegisterMessage(WantsToKick)


# @@protoc_insertion_point(module_scope)
