# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/motion/FootMotionCommand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Matrix_pb2 as Matrix__pb2
import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/motion/FootMotionCommand.proto',
  package='protobuf.message.motion',
  syntax='proto3',
  serialized_pb=_b('\n&message/motion/FootMotionCommand.proto\x12\x17protobuf.message.motion\x1a\x0cMatrix.proto\x1a\x0cVector.proto\"\x13\n\x11\x46ootMotionStopped\"\xaa\x01\n\x10\x46ootMotionUpdate\x12\r\n\x05phase\x18\x01 \x01(\x01\x12\x19\n\x11\x61\x63tiveForwardLimb\x18\x02 \x01(\r\x12\x19\n\nleftFoot2D\x18\x03 \x01(\x0b\x32\x05.vec3\x12\x1a\n\x0brightFoot2D\x18\x04 \x01(\x0b\x32\x05.vec3\x12\x19\n\nleftFoot3D\x18\x05 \x01(\x0b\x32\x05.mat4\x12\x1a\n\x0brightFoot3D\x18\x06 \x01(\x0b\x32\x05.mat4\"\xb8\x01\n\x12NextFootTargetInfo\x12\x1d\n\x0eleftFootSource\x18\x01 \x01(\x0b\x32\x05.vec3\x12\x1e\n\x0frightFootSource\x18\x02 \x01(\x0b\x32\x05.vec3\x12\x1a\n\x0bsupportMass\x18\x03 \x01(\x0b\x32\x05.vec3\x12\"\n\x13leftFootDestination\x18\x04 \x01(\x0b\x32\x05.vec3\x12#\n\x14rightFootDestination\x18\x05 \x01(\x0b\x32\x05.vec3\"#\n\x11\x46ootStepRequested\x12\x0e\n\x06status\x18\x01 \x01(\x08\"#\n\x11\x46ootStepCompleted\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x12\n\x10\x45nableFootMotion\"\x13\n\x11\x44isableFootMotionb\x06proto3')
  ,
  dependencies=[Matrix__pb2.DESCRIPTOR,Vector__pb2.DESCRIPTOR,])




_FOOTMOTIONSTOPPED = _descriptor.Descriptor(
  name='FootMotionStopped',
  full_name='protobuf.message.motion.FootMotionStopped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=114,
)


_FOOTMOTIONUPDATE = _descriptor.Descriptor(
  name='FootMotionUpdate',
  full_name='protobuf.message.motion.FootMotionUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phase', full_name='protobuf.message.motion.FootMotionUpdate.phase', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='activeForwardLimb', full_name='protobuf.message.motion.FootMotionUpdate.activeForwardLimb', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leftFoot2D', full_name='protobuf.message.motion.FootMotionUpdate.leftFoot2D', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rightFoot2D', full_name='protobuf.message.motion.FootMotionUpdate.rightFoot2D', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leftFoot3D', full_name='protobuf.message.motion.FootMotionUpdate.leftFoot3D', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rightFoot3D', full_name='protobuf.message.motion.FootMotionUpdate.rightFoot3D', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=287,
)


_NEXTFOOTTARGETINFO = _descriptor.Descriptor(
  name='NextFootTargetInfo',
  full_name='protobuf.message.motion.NextFootTargetInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leftFootSource', full_name='protobuf.message.motion.NextFootTargetInfo.leftFootSource', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rightFootSource', full_name='protobuf.message.motion.NextFootTargetInfo.rightFootSource', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='supportMass', full_name='protobuf.message.motion.NextFootTargetInfo.supportMass', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='leftFootDestination', full_name='protobuf.message.motion.NextFootTargetInfo.leftFootDestination', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rightFootDestination', full_name='protobuf.message.motion.NextFootTargetInfo.rightFootDestination', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=474,
)


_FOOTSTEPREQUESTED = _descriptor.Descriptor(
  name='FootStepRequested',
  full_name='protobuf.message.motion.FootStepRequested',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='protobuf.message.motion.FootStepRequested.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=511,
)


_FOOTSTEPCOMPLETED = _descriptor.Descriptor(
  name='FootStepCompleted',
  full_name='protobuf.message.motion.FootStepCompleted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='protobuf.message.motion.FootStepCompleted.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=513,
  serialized_end=548,
)


_ENABLEFOOTMOTION = _descriptor.Descriptor(
  name='EnableFootMotion',
  full_name='protobuf.message.motion.EnableFootMotion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=550,
  serialized_end=568,
)


_DISABLEFOOTMOTION = _descriptor.Descriptor(
  name='DisableFootMotion',
  full_name='protobuf.message.motion.DisableFootMotion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=589,
)

_FOOTMOTIONUPDATE.fields_by_name['leftFoot2D'].message_type = Vector__pb2._VEC3
_FOOTMOTIONUPDATE.fields_by_name['rightFoot2D'].message_type = Vector__pb2._VEC3
_FOOTMOTIONUPDATE.fields_by_name['leftFoot3D'].message_type = Matrix__pb2._MAT4
_FOOTMOTIONUPDATE.fields_by_name['rightFoot3D'].message_type = Matrix__pb2._MAT4
_NEXTFOOTTARGETINFO.fields_by_name['leftFootSource'].message_type = Vector__pb2._VEC3
_NEXTFOOTTARGETINFO.fields_by_name['rightFootSource'].message_type = Vector__pb2._VEC3
_NEXTFOOTTARGETINFO.fields_by_name['supportMass'].message_type = Vector__pb2._VEC3
_NEXTFOOTTARGETINFO.fields_by_name['leftFootDestination'].message_type = Vector__pb2._VEC3
_NEXTFOOTTARGETINFO.fields_by_name['rightFootDestination'].message_type = Vector__pb2._VEC3
DESCRIPTOR.message_types_by_name['FootMotionStopped'] = _FOOTMOTIONSTOPPED
DESCRIPTOR.message_types_by_name['FootMotionUpdate'] = _FOOTMOTIONUPDATE
DESCRIPTOR.message_types_by_name['NextFootTargetInfo'] = _NEXTFOOTTARGETINFO
DESCRIPTOR.message_types_by_name['FootStepRequested'] = _FOOTSTEPREQUESTED
DESCRIPTOR.message_types_by_name['FootStepCompleted'] = _FOOTSTEPCOMPLETED
DESCRIPTOR.message_types_by_name['EnableFootMotion'] = _ENABLEFOOTMOTION
DESCRIPTOR.message_types_by_name['DisableFootMotion'] = _DISABLEFOOTMOTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FootMotionStopped = _reflection.GeneratedProtocolMessageType('FootMotionStopped', (_message.Message,), dict(
  DESCRIPTOR = _FOOTMOTIONSTOPPED,
  __module__ = 'message.motion.FootMotionCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.FootMotionStopped)
  ))
_sym_db.RegisterMessage(FootMotionStopped)

FootMotionUpdate = _reflection.GeneratedProtocolMessageType('FootMotionUpdate', (_message.Message,), dict(
  DESCRIPTOR = _FOOTMOTIONUPDATE,
  __module__ = 'message.motion.FootMotionCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.FootMotionUpdate)
  ))
_sym_db.RegisterMessage(FootMotionUpdate)

NextFootTargetInfo = _reflection.GeneratedProtocolMessageType('NextFootTargetInfo', (_message.Message,), dict(
  DESCRIPTOR = _NEXTFOOTTARGETINFO,
  __module__ = 'message.motion.FootMotionCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.NextFootTargetInfo)
  ))
_sym_db.RegisterMessage(NextFootTargetInfo)

FootStepRequested = _reflection.GeneratedProtocolMessageType('FootStepRequested', (_message.Message,), dict(
  DESCRIPTOR = _FOOTSTEPREQUESTED,
  __module__ = 'message.motion.FootMotionCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.FootStepRequested)
  ))
_sym_db.RegisterMessage(FootStepRequested)

FootStepCompleted = _reflection.GeneratedProtocolMessageType('FootStepCompleted', (_message.Message,), dict(
  DESCRIPTOR = _FOOTSTEPCOMPLETED,
  __module__ = 'message.motion.FootMotionCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.FootStepCompleted)
  ))
_sym_db.RegisterMessage(FootStepCompleted)

EnableFootMotion = _reflection.GeneratedProtocolMessageType('EnableFootMotion', (_message.Message,), dict(
  DESCRIPTOR = _ENABLEFOOTMOTION,
  __module__ = 'message.motion.FootMotionCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.EnableFootMotion)
  ))
_sym_db.RegisterMessage(EnableFootMotion)

DisableFootMotion = _reflection.GeneratedProtocolMessageType('DisableFootMotion', (_message.Message,), dict(
  DESCRIPTOR = _DISABLEFOOTMOTION,
  __module__ = 'message.motion.FootMotionCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.DisableFootMotion)
  ))
_sym_db.RegisterMessage(DisableFootMotion)


# @@protoc_insertion_point(module_scope)
