# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/motion/ServoTarget.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/motion/ServoTarget.proto',
  package='protobuf.message.motion',
  syntax='proto3',
  serialized_pb=_b('\n message/motion/ServoTarget.proto\x12\x17protobuf.message.motion\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n\x0bServoTarget\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\n\n\x02id\x18\x02 \x01(\r\x12\x10\n\x08position\x18\x03 \x01(\x02\x12\x0c\n\x04gain\x18\x04 \x01(\x02\x12\x0e\n\x06torque\x18\x05 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_SERVOTARGET = _descriptor.Descriptor(
  name='ServoTarget',
  full_name='protobuf.message.motion.ServoTarget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='protobuf.message.motion.ServoTarget.time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf.message.motion.ServoTarget.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='protobuf.message.motion.ServoTarget.position', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gain', full_name='protobuf.message.motion.ServoTarget.gain', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='torque', full_name='protobuf.message.motion.ServoTarget.torque', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=209,
)

_SERVOTARGET.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ServoTarget'] = _SERVOTARGET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServoTarget = _reflection.GeneratedProtocolMessageType('ServoTarget', (_message.Message,), dict(
  DESCRIPTOR = _SERVOTARGET,
  __module__ = 'message.motion.ServoTarget_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.ServoTarget)
  ))
_sym_db.RegisterMessage(ServoTarget)


# @@protoc_insertion_point(module_scope)
