# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/motion/WalkCommand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/motion/WalkCommand.proto',
  package='protobuf.message.motion',
  syntax='proto3',
  serialized_pb=_b('\n message/motion/WalkCommand.proto\x12\x17protobuf.message.motion\x1a\x0cVector.proto\"\r\n\x0bWalkStarted\"\r\n\x0bWalkStopped\"<\n\x0bWalkCommand\x12\x15\n\rsubsumptionId\x18\x01 \x01(\x04\x12\x16\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x05.vec3\"$\n\x0bStopCommand\x12\x15\n\rsubsumptionId\x18\x01 \x01(\x04\"/\n\x0eNewWalkCommand\x12\x1d\n\x0evelocityTarget\x18\x01 \x01(\x0b\x32\x05.vec3\"0\n\x17\x45nableWalkEngineCommand\x12\x15\n\rsubsumptionId\x18\x01 \x01(\x04\"1\n\x18\x44isableWalkEngineCommand\x12\x15\n\rsubsumptionId\x18\x01 \x01(\x04\x62\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,])




_WALKSTARTED = _descriptor.Descriptor(
  name='WalkStarted',
  full_name='protobuf.message.motion.WalkStarted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=88,
)


_WALKSTOPPED = _descriptor.Descriptor(
  name='WalkStopped',
  full_name='protobuf.message.motion.WalkStopped',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=103,
)


_WALKCOMMAND = _descriptor.Descriptor(
  name='WalkCommand',
  full_name='protobuf.message.motion.WalkCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subsumptionId', full_name='protobuf.message.motion.WalkCommand.subsumptionId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='protobuf.message.motion.WalkCommand.command', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=165,
)


_STOPCOMMAND = _descriptor.Descriptor(
  name='StopCommand',
  full_name='protobuf.message.motion.StopCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subsumptionId', full_name='protobuf.message.motion.StopCommand.subsumptionId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=203,
)


_NEWWALKCOMMAND = _descriptor.Descriptor(
  name='NewWalkCommand',
  full_name='protobuf.message.motion.NewWalkCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='velocityTarget', full_name='protobuf.message.motion.NewWalkCommand.velocityTarget', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=252,
)


_ENABLEWALKENGINECOMMAND = _descriptor.Descriptor(
  name='EnableWalkEngineCommand',
  full_name='protobuf.message.motion.EnableWalkEngineCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subsumptionId', full_name='protobuf.message.motion.EnableWalkEngineCommand.subsumptionId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=254,
  serialized_end=302,
)


_DISABLEWALKENGINECOMMAND = _descriptor.Descriptor(
  name='DisableWalkEngineCommand',
  full_name='protobuf.message.motion.DisableWalkEngineCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subsumptionId', full_name='protobuf.message.motion.DisableWalkEngineCommand.subsumptionId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=304,
  serialized_end=353,
)

_WALKCOMMAND.fields_by_name['command'].message_type = Vector__pb2._VEC3
_NEWWALKCOMMAND.fields_by_name['velocityTarget'].message_type = Vector__pb2._VEC3
DESCRIPTOR.message_types_by_name['WalkStarted'] = _WALKSTARTED
DESCRIPTOR.message_types_by_name['WalkStopped'] = _WALKSTOPPED
DESCRIPTOR.message_types_by_name['WalkCommand'] = _WALKCOMMAND
DESCRIPTOR.message_types_by_name['StopCommand'] = _STOPCOMMAND
DESCRIPTOR.message_types_by_name['NewWalkCommand'] = _NEWWALKCOMMAND
DESCRIPTOR.message_types_by_name['EnableWalkEngineCommand'] = _ENABLEWALKENGINECOMMAND
DESCRIPTOR.message_types_by_name['DisableWalkEngineCommand'] = _DISABLEWALKENGINECOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WalkStarted = _reflection.GeneratedProtocolMessageType('WalkStarted', (_message.Message,), dict(
  DESCRIPTOR = _WALKSTARTED,
  __module__ = 'message.motion.WalkCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.WalkStarted)
  ))
_sym_db.RegisterMessage(WalkStarted)

WalkStopped = _reflection.GeneratedProtocolMessageType('WalkStopped', (_message.Message,), dict(
  DESCRIPTOR = _WALKSTOPPED,
  __module__ = 'message.motion.WalkCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.WalkStopped)
  ))
_sym_db.RegisterMessage(WalkStopped)

WalkCommand = _reflection.GeneratedProtocolMessageType('WalkCommand', (_message.Message,), dict(
  DESCRIPTOR = _WALKCOMMAND,
  __module__ = 'message.motion.WalkCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.WalkCommand)
  ))
_sym_db.RegisterMessage(WalkCommand)

StopCommand = _reflection.GeneratedProtocolMessageType('StopCommand', (_message.Message,), dict(
  DESCRIPTOR = _STOPCOMMAND,
  __module__ = 'message.motion.WalkCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.StopCommand)
  ))
_sym_db.RegisterMessage(StopCommand)

NewWalkCommand = _reflection.GeneratedProtocolMessageType('NewWalkCommand', (_message.Message,), dict(
  DESCRIPTOR = _NEWWALKCOMMAND,
  __module__ = 'message.motion.WalkCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.NewWalkCommand)
  ))
_sym_db.RegisterMessage(NewWalkCommand)

EnableWalkEngineCommand = _reflection.GeneratedProtocolMessageType('EnableWalkEngineCommand', (_message.Message,), dict(
  DESCRIPTOR = _ENABLEWALKENGINECOMMAND,
  __module__ = 'message.motion.WalkCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.EnableWalkEngineCommand)
  ))
_sym_db.RegisterMessage(EnableWalkEngineCommand)

DisableWalkEngineCommand = _reflection.GeneratedProtocolMessageType('DisableWalkEngineCommand', (_message.Message,), dict(
  DESCRIPTOR = _DISABLEWALKENGINECOMMAND,
  __module__ = 'message.motion.WalkCommand_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.motion.DisableWalkEngineCommand)
  ))
_sym_db.RegisterMessage(DisableWalkEngineCommand)


# @@protoc_insertion_point(module_scope)
