# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/support/nusight/DataPoint.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/support/nusight/DataPoint.proto',
  package='protobuf.message.support.nusight',
  syntax='proto3',
  serialized_pb=_b('\n\'message/support/nusight/DataPoint.proto\x12 protobuf.message.support.nusight\"\x96\x01\n\tDataPoint\x12\r\n\x05label\x18\x01 \x01(\t\x12\x11\n\x05value\x18\x02 \x03(\x02\x42\x02\x10\x01\x12>\n\x04type\x18\x03 \x01(\x0e\x32\x30.protobuf.message.support.nusight.DataPoint.Type\"\'\n\x04Type\x12\x0e\n\nFLOAT_LIST\x10\x00\x12\x0f\n\x0bROTATION_3D\x10\x02\x62\x06proto3')
)



_DATAPOINT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='protobuf.message.support.nusight.DataPoint.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FLOAT_LIST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROTATION_3D', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=189,
  serialized_end=228,
)
_sym_db.RegisterEnumDescriptor(_DATAPOINT_TYPE)


_DATAPOINT = _descriptor.Descriptor(
  name='DataPoint',
  full_name='protobuf.message.support.nusight.DataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='protobuf.message.support.nusight.DataPoint.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='protobuf.message.support.nusight.DataPoint.value', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='protobuf.message.support.nusight.DataPoint.type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DATAPOINT_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=228,
)

_DATAPOINT.fields_by_name['type'].enum_type = _DATAPOINT_TYPE
_DATAPOINT_TYPE.containing_type = _DATAPOINT
DESCRIPTOR.message_types_by_name['DataPoint'] = _DATAPOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataPoint = _reflection.GeneratedProtocolMessageType('DataPoint', (_message.Message,), dict(
  DESCRIPTOR = _DATAPOINT,
  __module__ = 'message.support.nusight.DataPoint_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.support.nusight.DataPoint)
  ))
_sym_db.RegisterMessage(DataPoint)


_DATAPOINT.fields_by_name['value'].has_options = True
_DATAPOINT.fields_by_name['value']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
