# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/support/nusight/DrawObjects.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Vector_pb2 as Vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/support/nusight/DrawObjects.proto',
  package='protobuf.message.support.nusight',
  syntax='proto3',
  serialized_pb=_b('\n)message/support/nusight/DrawObjects.proto\x12 protobuf.message.support.nusight\x1a\x0cVector.proto\"\x9d\x05\n\nDrawObject\x12\x41\n\x05shape\x18\x01 \x01(\x0e\x32\x32.protobuf.message.support.nusight.DrawObject.Shape\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x17\n\x08position\x18\x03 \x01(\x0b\x32\x05.vec3\x12\x18\n\tdirection\x18\x04 \x01(\x0b\x32\x05.vec3\x12\x15\n\x06target\x18\x05 \x01(\x0b\x32\x05.vec3\x12\r\n\x05width\x18\x06 \x01(\x02\x12\x0e\n\x06height\x18\x07 \x01(\x02\x12\x17\n\x08rotation\x18\x08 \x01(\x0b\x32\x05.vec3\x12\x15\n\x06\x63olour\x18\t \x01(\x0b\x32\x05.vec3\x12\x0e\n\x06radius\x18\n \x01(\x02\x12\x12\n\ntop_radius\x18\x0b \x01(\x02\x12\x15\n\rbottom_radius\x18\x0c \x01(\x02\x12\x17\n\x08vertices\x18\r \x03(\x0b\x32\x05.vec3\x12?\n\x04path\x18\x0e \x03(\x0b\x32\x31.protobuf.message.support.nusight.DrawObject.Path\x12\r\n\x05\x66\x61\x63\x65s\x18\x0f \x01(\r\x12\x12\n\nline_width\x18\x10 \x01(\x02\x12\x0e\n\x06length\x18\x11 \x01(\x02\x12\r\n\x05\x64\x65pth\x18\x12 \x01(\x02\x12\x0c\n\x04\x66ill\x18\x13 \x01(\x08\x12\x0f\n\x07timeout\x18\x14 \x01(\x02\x1a\x35\n\x04Path\x12\x17\n\x08position\x18\x01 \x01(\x0b\x32\x05.vec2\x12\x14\n\x0cparent_index\x18\x02 \x01(\r\"x\n\x05Shape\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x41RROW\x10\x01\x12\x07\n\x03\x42OX\x10\x02\x12\n\n\x06\x43IRCLE\x10\x03\x12\x0c\n\x08\x43YLINDER\x10\x04\x12\x0c\n\x08POLYLINE\x10\x05\x12\x0b\n\x07PYRAMID\x10\x06\x12\r\n\tRECTANGLE\x10\x07\x12\n\n\x06SPHERE\x10\x08\"L\n\x0b\x44rawObjects\x12=\n\x07objects\x18\x01 \x03(\x0b\x32,.protobuf.message.support.nusight.DrawObjectb\x06proto3')
  ,
  dependencies=[Vector__pb2.DESCRIPTOR,])



_DRAWOBJECT_SHAPE = _descriptor.EnumDescriptor(
  name='Shape',
  full_name='protobuf.message.support.nusight.DrawObject.Shape',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARROW', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOX', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CIRCLE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CYLINDER', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POLYLINE', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PYRAMID', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RECTANGLE', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPHERE', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=643,
  serialized_end=763,
)
_sym_db.RegisterEnumDescriptor(_DRAWOBJECT_SHAPE)


_DRAWOBJECT_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='protobuf.message.support.nusight.DrawObject.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='protobuf.message.support.nusight.DrawObject.Path.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_index', full_name='protobuf.message.support.nusight.DrawObject.Path.parent_index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=588,
  serialized_end=641,
)

_DRAWOBJECT = _descriptor.Descriptor(
  name='DrawObject',
  full_name='protobuf.message.support.nusight.DrawObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='protobuf.message.support.nusight.DrawObject.shape', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuf.message.support.nusight.DrawObject.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='protobuf.message.support.nusight.DrawObject.position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='protobuf.message.support.nusight.DrawObject.direction', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='protobuf.message.support.nusight.DrawObject.target', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='protobuf.message.support.nusight.DrawObject.width', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='protobuf.message.support.nusight.DrawObject.height', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation', full_name='protobuf.message.support.nusight.DrawObject.rotation', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colour', full_name='protobuf.message.support.nusight.DrawObject.colour', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius', full_name='protobuf.message.support.nusight.DrawObject.radius', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top_radius', full_name='protobuf.message.support.nusight.DrawObject.top_radius', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bottom_radius', full_name='protobuf.message.support.nusight.DrawObject.bottom_radius', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vertices', full_name='protobuf.message.support.nusight.DrawObject.vertices', index=12,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='protobuf.message.support.nusight.DrawObject.path', index=13,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='faces', full_name='protobuf.message.support.nusight.DrawObject.faces', index=14,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='line_width', full_name='protobuf.message.support.nusight.DrawObject.line_width', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='protobuf.message.support.nusight.DrawObject.length', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth', full_name='protobuf.message.support.nusight.DrawObject.depth', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fill', full_name='protobuf.message.support.nusight.DrawObject.fill', index=18,
      number=19, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timeout', full_name='protobuf.message.support.nusight.DrawObject.timeout', index=19,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DRAWOBJECT_PATH, ],
  enum_types=[
    _DRAWOBJECT_SHAPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=763,
)


_DRAWOBJECTS = _descriptor.Descriptor(
  name='DrawObjects',
  full_name='protobuf.message.support.nusight.DrawObjects',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='objects', full_name='protobuf.message.support.nusight.DrawObjects.objects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=765,
  serialized_end=841,
)

_DRAWOBJECT_PATH.fields_by_name['position'].message_type = Vector__pb2._VEC2
_DRAWOBJECT_PATH.containing_type = _DRAWOBJECT
_DRAWOBJECT.fields_by_name['shape'].enum_type = _DRAWOBJECT_SHAPE
_DRAWOBJECT.fields_by_name['position'].message_type = Vector__pb2._VEC3
_DRAWOBJECT.fields_by_name['direction'].message_type = Vector__pb2._VEC3
_DRAWOBJECT.fields_by_name['target'].message_type = Vector__pb2._VEC3
_DRAWOBJECT.fields_by_name['rotation'].message_type = Vector__pb2._VEC3
_DRAWOBJECT.fields_by_name['colour'].message_type = Vector__pb2._VEC3
_DRAWOBJECT.fields_by_name['vertices'].message_type = Vector__pb2._VEC3
_DRAWOBJECT.fields_by_name['path'].message_type = _DRAWOBJECT_PATH
_DRAWOBJECT_SHAPE.containing_type = _DRAWOBJECT
_DRAWOBJECTS.fields_by_name['objects'].message_type = _DRAWOBJECT
DESCRIPTOR.message_types_by_name['DrawObject'] = _DRAWOBJECT
DESCRIPTOR.message_types_by_name['DrawObjects'] = _DRAWOBJECTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DrawObject = _reflection.GeneratedProtocolMessageType('DrawObject', (_message.Message,), dict(

  Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), dict(
    DESCRIPTOR = _DRAWOBJECT_PATH,
    __module__ = 'message.support.nusight.DrawObjects_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.message.support.nusight.DrawObject.Path)
    ))
  ,
  DESCRIPTOR = _DRAWOBJECT,
  __module__ = 'message.support.nusight.DrawObjects_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.support.nusight.DrawObject)
  ))
_sym_db.RegisterMessage(DrawObject)
_sym_db.RegisterMessage(DrawObject.Path)

DrawObjects = _reflection.GeneratedProtocolMessageType('DrawObjects', (_message.Message,), dict(
  DESCRIPTOR = _DRAWOBJECTS,
  __module__ = 'message.support.nusight.DrawObjects_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.support.nusight.DrawObjects)
  ))
_sym_db.RegisterMessage(DrawObjects)


# @@protoc_insertion_point(module_scope)
