# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message/support/nusight/ReactionHandles.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message/support/nusight/ReactionHandles.proto',
  package='protobuf.message.support.nusight',
  syntax='proto3',
  serialized_pb=_b('\n-message/support/nusight/ReactionHandles.proto\x12 protobuf.message.support.nusight\"\x85\x01\n\x0fReactionHandles\x12I\n\x07handles\x18\x01 \x03(\x0b\x32\x38.protobuf.message.support.nusight.ReactionHandles.Handle\x1a\'\n\x06Handle\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x62\x06proto3')
)




_REACTIONHANDLES_HANDLE = _descriptor.Descriptor(
  name='Handle',
  full_name='protobuf.message.support.nusight.ReactionHandles.Handle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='protobuf.message.support.nusight.ReactionHandles.Handle.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='protobuf.message.support.nusight.ReactionHandles.Handle.enabled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=217,
)

_REACTIONHANDLES = _descriptor.Descriptor(
  name='ReactionHandles',
  full_name='protobuf.message.support.nusight.ReactionHandles',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='handles', full_name='protobuf.message.support.nusight.ReactionHandles.handles', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REACTIONHANDLES_HANDLE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=217,
)

_REACTIONHANDLES_HANDLE.containing_type = _REACTIONHANDLES
_REACTIONHANDLES.fields_by_name['handles'].message_type = _REACTIONHANDLES_HANDLE
DESCRIPTOR.message_types_by_name['ReactionHandles'] = _REACTIONHANDLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReactionHandles = _reflection.GeneratedProtocolMessageType('ReactionHandles', (_message.Message,), dict(

  Handle = _reflection.GeneratedProtocolMessageType('Handle', (_message.Message,), dict(
    DESCRIPTOR = _REACTIONHANDLES_HANDLE,
    __module__ = 'message.support.nusight.ReactionHandles_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.message.support.nusight.ReactionHandles.Handle)
    ))
  ,
  DESCRIPTOR = _REACTIONHANDLES,
  __module__ = 'message.support.nusight.ReactionHandles_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.message.support.nusight.ReactionHandles)
  ))
_sym_db.RegisterMessage(ReactionHandles)
_sym_db.RegisterMessage(ReactionHandles.Handle)


# @@protoc_insertion_point(module_scope)
